name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 8 for build
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          FROM_MAIL_MAILID: ${{ secrets.FROM_MAIL_MAILID }}
          FROM_MAIL_TEMP_PASSWORD: ${{ secrets.FROM_MAIL_TEMP_PASSWORD }}
          FROM_MAIL_PORT: ${{ secrets.FROM_MAIL_PORT }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

        run: mvn clean compile test-compile
      - name: Set up JDK 17 for SonarQube
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: SonarQube analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          FROM_MAIL_MAILID: ${{ secrets.FROM_MAIL_MAILID }}
          FROM_MAIL_TEMP_PASSWORD: ${{ secrets.FROM_MAIL_TEMP_PASSWORD }}
          FROM_MAIL_PORT: ${{ secrets.FROM_MAIL_PORT }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=journal-project_journalapp -Dsonar.organization=journal-project -Dsonar.host.url=https://sonarcloud.io
